# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [10]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]


# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

In [8]:
def same_first_last(nums):
    if nums[0] == nums[len(nums) - 1]:
        return True
    else:
        return False

print("Given list:", numbers_x)
print("Result is:", same_first_last(numbers_x))

print("Given list:", numbers_y)
print("Result is:", same_first_last(numbers_y))


Given list: [10, 20, 30, 40, 10]
Result is: True
Given list: [75, 65, 35, 75, 30]
Result is: False






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [15]:
#code here
import numpy as np 
# Creating two NumPy arrays 'x' and 'y' containing 2x3 matrices
x = np.array([[10, 3, 6],
                  [2, 4, 1]])

y = np.array([[3, 1, 19],
                  [4, 8, 9]])

print("Array1:") 
print(x)

print("Array2:") 
print(y)



Array1:
[[10  3  6]
 [ 2  4  1]]
Array2:
[[ 3  1 19]
 [ 4  8  9]]


In [16]:

# addition of arrays 'x' and 'y' using np.add()
print("\nElement-wise addition of arrays:")
print(np.add(x, y))

#product of arrays 'nums1' and 'nums2' using np.multiply()
print("\nElement-wise product of arrays:")
print(np.multiply(x, y))



Element-wise addition of arrays:
[[13  4 25]
 [ 6 12 10]]

Element-wise product of arrays:
[[ 30   3 114]
 [  8  32   9]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [26]:
import numpy as np

# Creating a 1D NumPy array
arr_1d = np.array([10, 15, 8, 2, 7, 5,15,14,5,1,0,13])

# Reshape arr_1d into a 2D array with dimensions (3, 4)
arr_2d = arr_1d.reshape(3, 4)
print("Reshaped 2D array:")
print(arr_2d)


# Concatenate  arrays horizontally using hstack()
arr_horizontal = np.hstack((arr_2d, arr_2d))
#horizontally concatenated array
print("\nConcatenated horizontally:")
print(arr_horizontal)


# Concatenating arrays vertically using vstack()
arr_vertical = np.vstack((arr_2d, arr_2d))

#vertically concatenated array
print("\nConcatenated vertically:")
print(arr_vertical)







Reshaped 2D array:
[[10 15  8  2]
 [ 7  5 15 14]
 [ 5  1  0 13]]

Concatenated horizontally:
[[10 15  8  2 10 15  8  2]
 [ 7  5 15 14  7  5 15 14]
 [ 5  1  0 13  5  1  0 13]]

Concatenated vertically:
[[10 15  8  2]
 [ 7  5 15 14]
 [ 5  1  0 13]
 [10 15  8  2]
 [ 7  5 15 14]
 [ 5  1  0 13]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [34]:
print("Welcome to the Online Store Shopping Cart!")

# Initialize an empty list to store items in the shopping cart
shopping_cart = []

# Displaying available products
electronic_products = ["Mobile", "Gadgets", "Tablet", "Laptop", "Smartwatch"]

print("\nAvailable products:")
for index, product in enumerate(electronic_products, 1):
    print(f"{index}. {product}")

# Main loop to iterate over the shopping process
while True:
    print("\nPlease select an option:")
    print("1. Add product to cart")
    print("2. View cart")
    print("q. Quit")

    user_input = input("Enter your choice (1, 2, q): ")

    if user_input.lower() == 'q':
        print("Contents of your shopping cart:")
        for item in shopping_cart:
            print(item)
        print("Thank you for your purchase!")
        break

    if user_input.isdigit():
        choice = int(user_input)

        if choice == 1:
            product_number = int(input("Enter the number corresponding to the product you want to add: "))
            if 1 <= product_number <= len(electronic_products):
                product_name = electronic_products[product_number - 1]
                shopping_cart.append(product_name)
                print(f"'{product_name}' has been added to your cart.")
            else:
                print("Invalid product number.")

        elif choice == 2:
            if shopping_cart:
                print("\nItems in your shopping cart:")
                for item in shopping_cart:
                    print(item)
            else:
                print("\nYour shopping cart is empty.")

        else:
            print("Invalid choice. Please enter a number between 1 and 2.")
    else:
        print("Invalid input. Please enter a number or 'q' to quit.")


Welcome to the Online Store Shopping Cart!

Available products:
1. Mobile
2. Gadgets
3. Tablet
4. Laptop
5. Smartwatch

Please select an option:
1. Add product to cart
2. View cart
q. Quit
Enter your choice (1, 2, q): 5
Invalid choice. Please enter a number between 1 and 2.

Please select an option:
1. Add product to cart
2. View cart
q. Quit
Enter your choice (1, 2, q): 1
Enter the number corresponding to the product you want to add: 5
'Smartwatch' has been added to your cart.

Please select an option:
1. Add product to cart
2. View cart
q. Quit
Enter your choice (1, 2, q): 1
Enter the number corresponding to the product you want to add: 3
'Tablet' has been added to your cart.

Please select an option:
1. Add product to cart
2. View cart
q. Quit
Enter your choice (1, 2, q): q
Contents of your shopping cart:
Smartwatch
Tablet
Thank you for your purchase!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [63]:
#code here

import random
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords


In [65]:


# Define the function to classify emails
def classify_emails(emails):
    important_keywords = ['urgent','important', 'action']
    promotions_keywords = ['sale', 'discount', 'offer']
    spam_keywords = ['lottery', 'spam', 'promotions','bumper','50%']

    important_emails = []
    promotions_emails = []
    spam_emails = []

    stop_words = set(stopwords.words('english'))

    for email in emails:
        email_lower = email.lower()
        words = word_tokenize(email_lower)
        filtered_words = [word for word in words if word not in stop_words]
        
        if any(keyword in filtered_words for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in filtered_words for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in filtered_words for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

# Generate random emails
emails = ['Important email about your Facebook account', 'very Limited time offer - 50% off', 'You won a lottery!','spam DO NOT LET GO BATA FLAT 50% OFF', 'Action required: Verify your email', 'Special discount for you',]

# Classify the emails
important_emails, promotions_emails, spam_emails = classify_emails(emails)

# Print the classified emails
print("Important Emails:")
print(important_emails)

print("\nPromotions Emails:")
print(promotions_emails)

print("\nSpam Emails:")
print(spam_emails)


Important Emails:
['Important email about your Facebook account', 'Action required: Verify your email']

Promotions Emails:
['very Limited time offer - 50% off', 'Special discount for you']

Spam Emails:
['You won a lottery!', 'spam DO NOT LET GO BATA FLAT 50% OFF']


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [ ]:
#code

english_words = ["food", "tree", "football", "sea", "cold"]
spanish_words = ["alimento", "árbol", "fútbol americano", "mar", "fría"]

# Main loop for dictionary lookup
print("Welcome to the English <--> Spanish Dictionary")
while True:
    word = input("> ")
    if word.lower() == 'exit':
        print("Exiting the dictionary. Goodbye!")
        break
    elif word.lower() == 'show':
        wordlist = input("Would you like to see the English or Spanish wordlist? ")
        if wordlist.lower() == 'english':
            print(','.join(english_words))
        elif wordlist.lower() == 'spanish':
            print(','.join(spanish_words))
        else:
            print("Invalid input. Please enter 'english' or 'spanish'.")
    else:
        word_lower = word.lower()
        if word_lower in english_words:
            index = english_words.index(word_lower)
            translation = spanish_words[index]
            print(f"The translation of '{word}' is '{translation}'.")
        elif word_lower in spanish_words:
            index = spanish_words.index(word_lower)
            translation = english_words[index]
            print(f"The translation of '{word}' is '{translation}'.")
        else:
            print(f"Translation for '{word}' is not available.")


Welcome to the English <--> Spanish Dictionary
> fire
Translation for 'fire' is not available.
> alimneto
Translation for 'alimneto' is not available.
> tree
The translation of 'tree' is 'árbol'.
> sea
The translation of 'sea' is 'mar'.
> show
Would you like to see the English or Spanish wordlist? spanish
alimento,árbol,fútbol americano,mar,fría
> show
Would you like to see the English or Spanish wordlist? none
Invalid input. Please enter 'english' or 'spanish'.
> english
Translation for 'english' is not available.
> show
Would you like to see the English or Spanish wordlist? english
food,tree,football,sea,cold


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [40]:
import pandas as pd

# Read the dataset
df = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Rank          16598 non-null  int64  
 1   Name          16598 non-null  object 
 2   Platform      16598 non-null  object 
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object 
 5   Publisher     16540 non-null  object 
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB


In [54]:
# Calculating the total global sales for all games in the dataset
total_global_sales = df['Global_Sales'].sum()
print("total global sales for all games is:" )
total_global_sales

total global sales for all games is:


8920.44

In [53]:
#the game with the highest global sales
highest_sales_game = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:")
highest_sales_game


Game with the highest global sales:


Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

In [52]:

#average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales)
avg_sales_per_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average sales for each region:")
avg_sales_per_region

Average sales for each region:


NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

In [51]:
# top 5 most popular game genres based on global sales
top_5_genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 most popular game genres based on global sales:")
top_5_genres

Top 5 most popular game genres based on global sales:


Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [50]:
# Calculating the total sales for each genre in each region and find the most popular genre in North America (NA_Sales)
total_sales_per_genre_in_each_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_in_na = total_sales_per_genre_in_each_region['NA_Sales'].idxmax()
print("Most popular genre in North America (NA_Sales):" )
most_popular_genre_in_na

Most popular genre in North America (NA_Sales):


'Action'

In [48]:

# Display last 10 rows
print("Last 10 rows:")
df.tail(10)

Last 10 rows:


Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [55]:

# the top 3 gaming platforms with the highest global sales
top_3_platforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("Top 3 gaming platforms with the highest global sales:")
top_3_platforms

Top 3 gaming platforms with the highest global sales:


Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [58]:
# Calculate the market share (percentage of global sales) for each genre
market_share_per_genre = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("Market share (percentage of global sales) for each genre:")
market_share_per_genre


Market share (percentage of global sales) for each genre:


Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [59]:

#the correlation coefficient between NA_Sales and EU_Sales
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print("Correlation coefficient between NA_Sales and EU_Sales:")
correlation_coefficient


Correlation coefficient between NA_Sales and EU_Sales:


0.7677267483702636